swagger: '2.0'
info:
 title: Zally
 description: Zally - Zalandos API linter service
 version: "0.0.1"
 contact:
   name: Felix Mueller
   email: felix.mueller2@zalando.de
host: "localhost:8080"
schemes:
  - https
basePath: /
parameters:
  Authorization:
    name: Authorization
    in: header
    description: OAUTH2 (IAM)
    required: true
    type: string
    format: OAUTH2 (IAM)

paths:
  '/apiViolations':
    post:
      summary:
        Retrieves list of API violations based on the uploaded swagger file
      description:
        Retrieves list of API violations based on the uploaded swagger file
      parameters:
        - $ref: '#/parameters/Authorization'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: API swagger is OK
          schema:
            $ref: '#/definitions/LintingResponse'
        400:
          description: Input file not parsable
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
        default:
          description: An array of error objects
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
      security:
        - oauth2:
          - uid

  '/items/{some_id}/item_level_1/{level1_id}/item-level-2/{level2_id}/item-level-3/{level3_id}/item-level-4':
    get:
      responses:
        200:
          description: Some description

definitions:
  LintingRequest:
    type: object
    description: Request containing a swagger definition file
    properties:
      api_defintion:
        type: object

  LintingResponse:
    type: object
    description:
    properties:
      violations:
        type: array
        items:
          $ref: '#/definitions/Violation'

  Violation:
    type: object
    description:
    required:
      - title
      - description
    properties:
      title:
        type: string
      description:
        type: string
      lineNumber:
        type: integer
      column_number:
        type: integer
      violationType:
        type: string
        enum:
        - MUST
        - SHOULD
        - COULD
